---
title: "EDA for Research on English Instruction"
author: "Lemi Daba"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

rm(list = ls())

# preliminaries
library(haven)
library(tidyverse)
library(janitor)
library(lubridate)
library(AER)
library(stargazer)
library(scales)
library(broom)
library(car)
library(tidytext)

theme_set(theme_light())

# load data
wave1 <- read_dta("data/ethiopia_wave_1.dta")
wave2 <- read_dta("data/ethiopia_wave_2.dta")

```

## Cleaning:

```{r}

schsurv_raw <- wave1 %>% 
  select(UNIQUEID:REGION, SCHGRDE, LANG, STDMEAL, 
         STMOMED, STDADED, MTH_TCHLVLEDC, MTH_TCHLVTCTR,
         HTGRDMTH, HTSCHOWN, STDLNGHM, starts_with("STLNG"), 
         SCSLNGIN, FCLIBR, RAW_MAT1, RAW_ENG1) %>% 
  left_join(
    wave2 %>% 
      select(UNIQUEID, RAW_MAT2, RAW_ENG2), 
    by = "UNIQUEID") 
  

# function to standardize test scores
standardize <- function(x){ 
  z <- (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE) 
  return( z)
}

# create variables
schsurv <- schsurv_raw %>% 
  clean_names() %>% 
  # convert labelled columns to factors (haven::as_factor())
  mutate_if(is.labelled, as_factor, levels = "labels") %>% 
  mutate(
    # standardize test scores:
    std_eng_w1 = standardize(raw_eng1),
    std_maths_w1 = standardize(raw_mat1),
    std_eng_w2 = standardize(raw_eng2),
    std_maths_w2 = standardize(raw_mat2),
 
    # section id:
    sect_id = str_c(schlid, sectionid)
    ) %>% 
  # retain only grade 8 students
  filter(schgrde == "Grade 8") %>% 
  rename(
    id = uniqueid, 
    home_lang = stdlnghm,
    locality = urban, 
    owned_by = htschown,
    math_test_lang = lang
    )

```

What languages can students speak?

```{r}

lang_nested <- schsurv %>% 
  select(id, starts_with("stlng")) %>% 
  pivot_longer(stlng01:stlng11, names_to = "can_speak", 
               values_to = "value") %>% 
  mutate(
    can_speak = case_when(
      can_speak == "stlng01" ~ "Afarigna",
      can_speak == "stlng02" ~ "Amarigna",
      can_speak == "stlng03" ~ "Guraghigna",
      can_speak == "stlng04" ~ "Hadiyigna",
      can_speak == "stlng05" ~ "Afaan Oromo",
      can_speak == "stlng06" ~ "Sidamigna",
      can_speak == "stlng07" ~ "Silitigna",
      can_speak == "stlng08" ~ "Af-Somali",
      can_speak == "stlng09" ~ "Tigrigna",
      can_speak == "stlng10" ~ "Welaytigna",
      can_speak == "stlng11" ~ "English",
    ),
  ) %>% 
  filter(value == "Yes") %>% 
  select(-value) %>% 
  group_by(id) %>% 
  nest()

vect <- function(tbl) {
  tbl$can_speak %>% 
    paste(collapse = "; ")
}

langs_spoken <- lang_nested %>% 
  mutate(can_speak = map(data, vect)) %>% 
  unnest(can_speak) %>% 
  select(-data) %>% 
  ungroup()

# join with 'schsurv':
schsurv <- schsurv %>% 
  left_join(langs_spoken, by = "id") %>% 
  select(-starts_with("stlng"))

```

```{r}
# Remove unnecessary objects
rm(lang_nested, langs_spoken, vect)
```



## Analysis

By region and locality (i.e., urban vs. rural):

```{r}

by_region_local <- schsurv %>% 
  group_by(region, locality) %>% 
  summarize(n = n(), .groups = "drop") %>% 
  mutate(prop = n / sum(n)) %>% 
  mutate(region = fct_reorder(region, n, sum)) 

by_region_local %>% 
  ggplot(aes(prop, region, fill = locality)) +
  geom_col() +
  scale_x_continuous(labels = percent_format()) +
  labs(title = "Distribution of Observations by Region and Locality Type",
       fill = "Locality",
       x = "Percent", y = "Region")

by_region_local %>% 
  ggplot(aes(region, n, fill = locality)) +
  geom_col() +
  labs(y = "# of observations", x = "Region", 
       fill = "Locality",
       title = "Count of Observations by Region and Locality Type",)

```


```{r}

scores_region <- schsurv %>% 
  filter(region != "Addis Ababa") %>% 
  group_by(region, locality) %>% 
  summarize(
    mean_maths2_std = mean(std_maths_w2, na.rm = TRUE),
    mean_maths2_raw = mean(raw_mat2, na.rm = TRUE),
    n = n(),
    .groups = "drop"
    ) 

# Raw scores:
scores_region %>% 
  filter(region != "Addis") %>% 
  mutate(region = reorder_within(region, mean_maths2_raw, locality)) %>% 
  ggplot(aes(region, mean_maths2_raw)) +
  geom_col() +
  facet_wrap(~ locality, scales = "free_x") +
  scale_x_reordered() +
  labs(x = "Region", y = "Maths Score (Raw)")

# Standardized scores:
scores_region %>% 
  filter(region != "Addis") %>% 
  mutate(region = reorder_within(region, mean_maths2_raw, locality)) %>% 
  ggplot(aes(region, mean_maths2_std)) +
  geom_col() +
  facet_wrap(~ locality, scales = "free_x") +
  scale_x_reordered()

```

By region and type of school (Private, Gov't, etc.)

```{r}

schsurv %>% 
  count(owned_by)

schsurv %>% 
  filter(!is.na(owned_by)) %>% 
  filter(region != "Addis Ababa") %>% 
  group_by(region, owned_by) %>% 
  summarize(
    mean_maths2_std = mean(std_maths_w2, na.rm = TRUE),
    mean_maths2_raw = mean(raw_mat2, na.rm = TRUE),
    n = n(),
    .groups = "drop"
    ) %>% 
  mutate(
    region = fct_reorder(region, mean_maths2_raw),
    owned_by = fct_reorder(owned_by, mean_maths2_raw)
         ) %>% 
  ggplot(aes(region, mean_maths2_raw)) +
  geom_col() +
  facet_wrap(~ owned_by, nrow = 2)
  
```

```{r}

schsurv %>% 
  count(region, sort = T)

schsurv %>% 
  filter(
    region == "Oromia",
    home_lang == "Afaan Oromo" 
  ) %>% 
  filter(str_detect(can_speak, "Afaan Oromo")) %>% 
  summarize(n = n())

schsurv %>% 
  filter(
    region == "Oromia",
    home_lang == "Amarigna" 
  ) %>% 
  # how many can speak only Amharic?
  filter(can_speak == "Amarigna") %>% 
  summarize(n = n())

schsurv %>% 
  filter(
    region == "Amhara",
    home_lang == "Amarigna" 
  ) %>% 
  filter(str_detect(can_speak, "Afaan Oromo")) %>% 
  summarize(n = n())

```


































